USE NigeriaBasketballAssociation;
GO

ALTER TABLE HoiDong
ADD MaHoiDong_New VARCHAR(20);
GO

UPDATE HoiDong
SET MaHoiDong_New = 'HD' + CAST(MaHoiDong AS VARCHAR(10));
GO

ALTER TABLE ThanhVienHoiDong DROP CONSTRAINT FK_TVHD_HoiDong;
GO

ALTER TABLE DanhGiaHoiDong DROP CONSTRAINT FK_DanhGia_HoiDong;
GO

ALTER TABLE HoiDong DROP CONSTRAINT PK__HoiDong__...;
GO

ALTER TABLE HoiDong
DROP COLUMN MaHoiDong;
GO

EXEC sp_rename 'HoiDong.MaHoiDong_New', 'MaHoiDong', 'COLUMN';
GO

ALTER TABLE ThanhVienHoiDong
ADD CONSTRAINT FK_TVHD_HoiDong
FOREIGN KEY (MaHoiDong) REFERENCES HoiDong(MaHoiDong);
GO

ALTER TABLE DanhGiaHoiDong
ADD CONSTRAINT FK_DanhGia_HoiDong
FOREIGN KEY (MaHoiDong) REFERENCES HoiDong(MaHoiDong);
GO